name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the main branch
  pull_request:
    branches:
      - main  # Trigger when a PR is created to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (or another version you are using)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project using Maven
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      # Deploy the application (you may need to adjust this to match Render's deployment setup)
      - name: Deploy to Render
        run: |
          # Assuming you have a Render CLI installed or a Render-specific deployment setup
          # Deploy with Render CLI
          curl -sSL https://render.com/downloads/render-cli.sh | bash
          render login --apiKey ${{ secrets.RENDER_API_KEY }}
          render deploy --service your-service-name
