name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the main branch
  pull_request:
    branches:
      - main  # Trigger when a PR is created to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project using Maven
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      # Install Render CLI
      - name: Install Render CLI
        run: |
          curl -sSL https://cli.render.com | bash
          render --version  # Verify that the Render CLI is installed

      # Deploy the application to Render
      - name: Deploy to Render
        run: |
          render login --apiKey ${{ secrets.RENDER_API_KEY }}  # Use GitHub secret for the API key
          render deploy --service budget-tracker-backend
