name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow when a PR is created for the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the build process

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 for the build
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Set Java version to 21
          distribution: 'temurin'  # Use the Temurin distribution of Java

      # Cache Maven dependencies to speed up builds on subsequent runs
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Cache Maven repository directory
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Use pom.xml hash to cache dependencies
          restore-keys: |
            ${{ runner.os }}-maven-  # Restore previous cache if the exact match is not found

      # Build the project using Maven
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests  # Use Maven wrapper to clean, build, and skip tests

      # Deploy the application to Render using GitHub API
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"service":"budget-tracker-backend"}'
