name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project using Maven
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      # Install Render CLI
      - name: Install Render CLI
        run: |
          curl -sSL https://github.com/renderinc/render-cli/releases/download/v0.0.5/render-cli-linux-amd64 -o render-cli
          chmod +x render-cli
          sudo mv render-cli /usr/local/bin/render
          render --version

      # Deploy the application to Render
      - name: Deploy to Render
        run: |
          echo "$RENDER_API_KEY" | render login --apiKey
          render deploy --service budget-tracker-backend
